version: '3'

services:
  app:
    container_name: ts-node-app
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    restart: always
    env_file: .env
    expose:
      - 3000
    ports:
      - 3000:3000
    environment: 
      - MONGODB_URL=mongodb+srv://yorknguyen3008:Hailung3008.@cluster0.yb35uvy.mongodb.net/nodedatabase
      - CLIENT_URL=http://localhost:5000 
